version: '3.8'

services:
  db:
    image: mongo:8.0.3
    container_name: academy_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academy_backend
    ports:
      - "9000:8000"
    env_file:
      - ./backend/.env
    environment:
      - SECRET_KEY=supersecretkeyforacademydevelopment123!#
    depends_on:
      - db
    restart: always

  frontend:
    image: node:20.7.0-slim
    container_name: academy_frontend
    working_dir: /workspace
    volumes:
      - ./frontend:/workspace
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://backend:8000/api
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:
